### ISSUE TITLE
Add this new soundpack to the repository

### ISSUE THREAD

**Issue by PartridgeProgramming** [remyroy/CDDA-Game-Launcher#490] opened 2020-09-17 03:54 UTC
* Name: Otopack
* Url: https://github.com/Kenan2000/Otopack-Mods-Updates
* Author: Kenan2000
* Homepage: https://github.com/Kenan2000
* Soundpack not found in version: 1.4.11

**Comment by remyroy** [comment] 2020-09-17 19:11
This is a duplicate of #484 . This soundpack was included recently and will be part of the next release.

**Closed by remyroy** 2020-09-17 19:11 UTC
