### ISSUE TITLE
Unhandled exception: [TypeError]

### ISSUE THREAD

**Issue by chesshunter** [remyroy/CDDA-Game-Launcher#275] opened 2019-04-30 17:55 UTC
* Description: [Launcher failed to start]
* Version: 1.3.16
* OS: Windows-10-10.0.14393 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by remyroy** [comment] 2019-04-30 18:08
This is a duplicate of #271 .

**Closed by remyroy** 2019-04-30 18:08 UTC
