### ISSUE TITLE
Unhandled exception: Launcher crashing due to a super old game folder

### ISSUE THREAD

**Issue by DillonSimeone** [remyroy/CDDA-Game-Launcher#74] opened 2016-09-08 01:46 UTC
* Description: After a long time of not playing, I ran the launcher again, with my OLD game still in the target folder. I deleted the old game folder after encountering this error, and it resolved the issue! 
* Version: 1.3.2
* Type: `<class 'UnicodeDecodeError'>`
* Value: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence
* Traceback:
```
  File "cddagl\ui.py", line 2475, in copy_next_dir
  File "cddagl\ui.py", line 2526, in post_extraction_step2
  File "cddagl\ui.py", line 2423, in asset_name

```

**Comment by remyroy** [comment] 2016-09-18 15:29
Duplicate of #75.

**Closed by remyroy** 2016-09-18 15:29 UTC
