### ISSUE TITLE
Unhandled exception: Attribute Error on launch

### ISSUE THREAD

**Issue by nuke147** [remyroy/CDDA-Game-Launcher#93] opened 2017-01-05 02:25 UTC
* Description: Updated to most recent version with the launcher, then attempted to launch.  Delivered this error. Disabled all mods leaving only core cdda active, and attempted to launch again, generating this report.
* Version: 1.3.8.2
* OS: Windows-7-6.1.7601-SP1 (64-bit)
* Type: `<class 'AttributeError'>`
* Value: 'NoneType' object has no attribute 'replace'
* Traceback:
```
  File "cddagl\ui.py", line 984, in launch_game
  File "cddagl\ui.py", line 1025, in launch_game_process
  File "html\__init__.py", line 19, in escape

```

**Comment by remyroy** [comment] 2017-02-08 19:39
This is a duplicate of #96 and it should be fixed now.

**Closed by remyroy** 2017-02-08 19:39 UTC
