### ISSUE TITLE
jenkins-latest/Windows_x64/Tiles (5155)

### ISSUE THREAD

**Issue by Honcharuk** [remyroy/CDDA-Game-Launcher#63] opened 2016-06-29 18:28 UTC
No executable found in the downloaded archive.

**Comment by remyroy** [comment] 2016-06-29 18:32
This is a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/17422 . The issue is with the game builds, not the launcher. Use build 5151 which has an executable.

**Closed by remyroy** 2016-06-29 18:32 UTC

**Comment by Xelat84** [comment] 2016-06-29 23:02
BTW launcher hangs when trying to update to build with missing exe. Probably need to make checks for that case.

**Comment by remyroy** [comment] 2016-06-29 23:18
@Xelat84 That was fixed in 1.3

**Comment by Xelat84** [comment] 2016-06-29 23:21
@remyroy yeah, thanks for that! Just checked for updates few hours ago and there was none. Now I see new update! Good job! :+1:
