### ISSUE TITLE
Installer detected as trojan?

### ISSUE THREAD

**Issue by tristanICS** [remyroy/CDDA-Game-Launcher#440] opened 2020-04-09 21:42 UTC
https://www.virustotal.com/gui/file/6595577689ab1fb31660a4a1ea047d9924580ce256ea0a525adc2e0233a5d81a/detection

**Comment by remyroy** [comment] 2020-04-09 22:14
This is a duplicate of #434

**Closed by remyroy** 2020-04-09 22:14 UTC
