### ISSUE TITLE
Unhandled exception: [Crashed while changing directory]

### ISSUE THREAD

**Issue by drynyn** [remyroy/CDDA-Game-Launcher#76] opened 2016-09-15 19:02 UTC
- Description: [Downloaded, ran, then changed the game directory. Crash. Happened twice, on third time I loaded it the directory path had been changed and I proceeded to install. ]
- Version: 1.3.2
- Type: `<class 'TypeError'>`
- Value: unsupported operand type(s) for +: 'NoneType' and 'str'
- Traceback:

```
  File "cddagl\ui.py", line 1134, in dc_index_changed
  File "cddagl\ui.py", line 1177, in game_directory_changed
  File "cddagl\ui.py", line 1093, in update_mods
  File "cddagl\ui.py", line 7182, in game_dir_changed
  File "cddagl\ui.py", line 7108, in add_mod

```

**Comment by remyroy** [comment] 2016-09-15 19:03
Thanks for the report. I'll check it out when I have some time.

**Comment by remyroy** [comment] 2016-09-18 15:19
Do you still have that game directory? If so, could you zip it and send it to me?

**Comment by remyroy** [comment] 2016-09-18 15:32
This is a duplicate of #49. I would really like to have a game directory that crashes like this so I can investigate more.

**Closed** 2016-11-24 00:44 UTC

**Comment by drynyn** [comment] 2016-11-24 02:14
Sorry mate, only got an email notification when you closed this. Will see if I still have it installed. Will probably have to try to reproduce it.
