### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by qifengxun** [remyroy/CDDA-Game-Launcher#337] opened 2019-05-14 01:44 UTC
* Description: [Enter what you did and what happened]
* Version: 1.3.22
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'json.decoder.JSONDecodeError'>`
* Value: Expecting value: line 1 column 1 (char 0)
* Traceback:
```
  File "cddagl\ui.py", line 3207, in lb_http_finished
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode

```

**Comment by remyroy** [comment] 2019-05-15 20:30
This seems like a duplicate of #338

**Closed** 2019-06-02 17:55 UTC
