### ISSUE TITLE
Unhandled exception: [Crash on update list refresh]

### ISSUE THREAD

**Issue by AugustusImperator** [remyroy/CDDA-Game-Launcher#272] opened 2019-04-30 16:54 UTC
* Description: [Refreshed the list of updates and it crashed. Then tried to reopen the launcher and it crashes to this when trying to refresh the updates automatically. Will try to reinstall the launcher.]
* Version: 1.3.15
* OS: Windows-10-10.0.17763 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by remyroy** [comment] 2019-04-30 17:02
This seems to be a duplicate of #271 . It seems systemic. I will investigate soon.

**Closed by remyroy** 2019-04-30 17:02 UTC
