### ISSUE TITLE
Unhandled exception: New, need help.

### ISSUE THREAD

**Issue by SomeGuyHere** [remyroy/CDDA-Game-Launcher#279] opened 2019-04-30 18:49 UTC
* Description: I accidentally hit "previous version" on the launcher and then panicked, closed the launcher preemptively as a reaction. After that I tried opening the launcher, it obviously crashed.
I just want to know how to fix it before doing anything stupid again by accident.
* Version: 1.3.16
* OS: Windows-10-10.0.17134 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3078, in lb_http_finished

```

**Comment by remyroy** [comment] 2019-04-30 18:51
This is a duplicate of #271 and it should be fixed in 1.3.19 .

**Closed by remyroy** 2019-04-30 18:51 UTC
