### ISSUE TITLE
CDDA Game Launcher files cannot be inside Game directory! (1.42)

### ISSUE THREAD

**Issue by ZhilkinSerg** [remyroy/CDDA-Game-Launcher#379] opened 2019-09-04 14:14 UTC
Something is not right with game and launcher paths checking in launcher version 1.42 - launcher tells "Unknown version - Reason: CDDA Game Launcher files cannot be inside Game directory!" while launcher and game are in different folders ("C:\Games\cdda" and "C:\Games\cdda-launcher").

![image](https://user-images.githubusercontent.com/16213433/64262683-21e02780-cf37-11e9-9cf6-4983862ce73e.png)

**Comment by ZhilkinSerg** [comment] 2019-09-04 14:18
Removing `cdda` prefix from launcher folder names resolves the issue. I guess there is some kind of regex used for path matching?

**Comment by remyroy** [comment] 2019-09-04 15:36
This is a duplicate of #377 . There will be a quick bug fix release soon with it.

**Comment by remyroy** [comment] 2019-09-04 17:19
This has been fixed and the fix is part of the latest 1.4.3 release.

**Closed by remyroy** 2019-09-04 17:19 UTC

**Comment by ZhilkinSerg** [comment] 2019-09-04 18:35
Thanks!
