### ISSUE TITLE
How can I treat the fatal error detected problem "Failed to execute script pyi_rth_pkgres

### ISSUE THREAD

**Issue by MelexKrieger** [remyroy/CDDA-Game-Launcher#429] opened 2020-04-02 10:31 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**

**Comment by remyroy** [comment] 2020-04-02 14:10
Which version of the launcher are you using?

**Comment by NeedFI** [comment] 2020-04-02 18:10
Excuse me, but I'm also having this issue, in my case, it happens with every version you've launched after the 0.E release. 
Even downloaded the vc_redist you provided again, but unfortunately it does not seem to the cause.
Also happens with portable versions and from the version 1.4.4 or below, all seems to work fine.

**Comment by remyroy** [comment] 2020-04-02 18:26
I've just made a debug release to get more information regarding your issue. You can download it here: https://www.dropbox.com/s/i2xlmpn8u4bwy37/cddagl_portable_v1.4.7.debug.zip?dl=1

Extract the archive, start the launcher using the `launcher-debug.bat` file. It should create a `debug.txt` file with some logs. Send me back that `debug.txt` file and that should give me more information regarding your issue.

**Comment by NeedFI** [comment] 2020-04-02 22:44
[debug.txt](https://github.com/remyroy/CDDA-Game-Launcher/files/4424104/debug.txt)
Know it wasn't me that opened the issue, but gonna send it too as I'd like to see it fixed seeing how it makes managing the experimental version easier.

**Comment by remyroy** [comment] 2020-04-02 23:54
Try this new debug version. See if it works. If not, send me the new `debug.txt` file you get by starting the launcher with the `launcher-debug.bat` file: https://www.dropbox.com/s/zl126shhxc5q0ti/cddagl_portable_v1.4.7.debug.py37.zip?dl=1

**Comment by MelexKrieger** [comment] 2020-04-03 02:36
I played this game last 2 days, then I started to update it yesterday. After the update. the launcher cannot be open and this problem came in: "Failed to execute script pyi_rth_pkgres"

**Comment by MelexKrieger** [comment] 2020-04-03 02:46
Are this the launcher-debug.bat and debug.txt?
![debug](https://user-images.githubusercontent.com/62881095/78318857-6c428900-7598-11ea-85d3-649b8cb6292d.PNG)

**Comment by MelexKrieger** [comment] 2020-04-03 02:48
[debug.txt](https://github.com/remyroy/CDDA-Game-Launcher/files/4424799/debug.txt)

**Comment by remyroy** [comment] 2020-04-03 03:43
@MelexKrieger You are having the same issue as @NeedFI . Please try the new debug release like I mentionned in https://github.com/remyroy/CDDA-Game-Launcher/issues/429#issuecomment-608153179_

**Comment by NeedFI** [comment] 2020-04-03 04:43
For me this second debug version of yours worked like a charm, much obliged.

**Comment by MelexKrieger** [comment] 2020-04-03 04:59
Problem solved! :)

**Comment by remyroy** [comment] 2020-04-03 12:19
This issue seems to be caused by bundling the launcher with Python 3.8. We'll downgrade to Python 3.7 for the next release and it should solve it.

**Comment by remyroy** [comment] 2020-04-03 14:12
It should be fixed now with the release of 1.4.8 .

**Closed by remyroy** 2020-04-03 14:12 UTC
