### ISSUE TITLE
Directory is not empty - CRASH

### ISSUE THREAD

**Issue by Malkeus** [remyroy/CDDA-Game-Launcher#18] opened 2016-01-13 20:44 UTC
This seems to be caused by having an explorer window open to previous_version/data/mods while updating. I don't have the exact crash message on hand, if it happens again I'll post it here.

**Comment by remyroy** [comment] 2016-01-13 22:55
The crash message would help, yes.

**Comment by remyroy** [comment] 2016-01-14 13:48
Like I mentioned in #19, I think the best thing we can do it show some kind of message box asking the user to retry or cancel and try to identify which process is holding the resource.

**Comment by Malkeus** [comment] 2016-01-14 13:54
I agree on the retry or cancel. Everything was ok once I deleted the previous_version directory.

**Comment by remyroy** [comment] 2016-01-17 05:07
This is a duplicate of #19 which has just been resolved.

**Closed by remyroy** 2016-01-17 05:07 UTC
