### ISSUE TITLE
Unhandled exception: [Launcher crashing on updating CDDA]

### ISSUE THREAD

**Issue by GradusNL** [remyroy/CDDA-Game-Launcher#61] opened 2016-06-29 14:12 UTC
* Description: [Tried to update my CDDA to the latest experimental, patcher stopped patching without showing any progress bars of any kind only showing the cancel installation option, I then pressed it upon which the launcher crashed]
* Version: 1.2
* Type: `<class 'AttributeError'>`
* Value: 'GameDirGroupBox' object has no attribute 'opened_exe'
* Traceback:
```
  File "cddagl\ui.py", line 1924, in update_game

```

**Comment by remyroy** [comment] 2016-06-29 14:13
This is most likely a duplicate of #60 . Thanks for the report.

**Comment by remyroy** [comment] 2016-06-29 14:17
The latest experimental release do not have an executable file which is why it crash like this. Let me put something to prevent that.

**Comment by remyroy** [comment] 2016-06-29 14:58
This should be fixed with changes in 2a12214266f68ac1a194b31f4924a7b7168c2235. A new version is being built to include this.

**Closed by remyroy** 2016-06-29 14:58 UTC
