### ISSUE TITLE
Unhandled Exception: Crash on startup

### ISSUE THREAD

**Issue by Rosencratz** [remyroy/CDDA-Game-Launcher#339] opened 2019-05-15 05:34 UTC
* Description: Crash on start
* Version: 1.3.22
* OS: Windows-10-10.0.17763 (64-bit)
* Type: `<class 'json.decoder.JSONDecodeError'>`
* Value: Expecting value: line 1 column 1 (char 0)
* Traceback:
```
  File "cddagl\ui.py", line 3207, in lb_http_finished
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode

```

**Comment by remyroy** [comment] 2019-05-15 20:29
This seems like a duplicate of #338

**Comment by Rosencratz** [comment] 2019-05-17 05:38
> This seems like a duplicate of #338

Seems to be, yeah. So the advice I am getting is that there's a limit to how often the launcher can interact with github so I just need to pick a separate time to run the launcher?

**Comment by remyroy** [comment] 2019-05-17 18:38
The next version of the launcher is going to handle this issue in a better way if this is really caused by the rate limit from the Github API. While it may not be able to list the available builds, it will tell you why and how long you're going to wait until you can refresh.

Eventually, it might be a good idea to enable authenticated requests which are limited to 5000 requests per hour (instead of 60) by integrating your Github account credentials with the launcher. We'll see.

**Comment by Rosencratz** [comment] 2019-05-18 02:54
> The next version of the launcher is going to handle this issue in a better way if this is really caused by the rate limit from the Github API. While it may not be able to list the available builds, it will tell you why and how long you're going to wait until you can refresh.
> 
> Eventually, it might be a good idea to enable authenticated requests which are limited to 5000 requests per hour (instead of 60) by integrating your Github account credentials with the launcher. We'll see.

Ah, alright then. I look forward to the new launcher. And don't see I shouldn't if it makes things easier. Thanks!

**Closed** 2019-05-18 06:37 UTC
