### ISSUE TITLE
mutated changes

### ISSUE THREAD

**Issue by TheMachinist699** [remyroy/CDDA-Game-Launcher#403] opened 2019-12-22 23:16 UTC
* Name: [Enter the name of the mod]
* Url: [Enter the Url where we can find the mod]
* Author: [Enter the name of the author]
* Homepage: [Enter the Url of the author website or where the mod was published]
* Mod not found in version: 1.4.4

**Comment by remyroy** [comment] 2019-12-27 17:02
This is a duplicate of #404

**Closed by remyroy** 2019-12-27 17:02 UTC
