### ISSUE TITLE
An Unhandled exception: [The CDDA Game Launcher just Crached]

### ISSUE THREAD

**Issue by Dosbally** [remyroy/CDDA-Game-Launcher#65] opened 2016-07-18 00:41 UTC
- version: 1.3.2
- Type: <class 'UnicodeDecodeError'>
- Value: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence
- Traceback:
`File "cddagl\ui.py", line 2475, in copy_next_dir

File "cddagl\ui.py", line 2526, in post_extraction_step2
File "cddagl\ui.py", line 2423, in asset_name`

**Comment by remyroy** [comment] 2016-07-20 01:03
Thanks for the report. I'll check it out.

**Comment by remyroy** [comment] 2016-09-18 15:31
Duplicate of #75.

**Closed by remyroy** 2016-09-18 15:31 UTC
