### ISSUE TITLE
Unhandled exception: [I tried to update the game after update the launcher]

### ISSUE THREAD

**Issue by Katanasoul91** [remyroy/CDDA-Game-Launcher#428] opened 2020-04-02 01:26 UTC
* Description: [Enter what you did and what happened]
* Version: 1.4.5
* OS: Windows-10-10.0.17763-SP0 (64-bit)
* Type: `<class 'FileNotFoundError'>`
* Value: [WinError 3] El sistema no puede encontrar la ruta especificada: 'C:\\Users\\Diego\\AppData\\Local\\Programs\\CDDA Game Launcher\\cdda\\previous_version\\font'
* Traceback:
```
  File "cddagl\ui\views\main.py", line 2339, in copy_next_soundpack
  File "cddagl\ui\views\main.py", line 2511, in post_extraction_step3
  File "cddagl\ui\views\main.py", line 2392, in preserve_custom_fonts

```

**Comment by remyroy** [comment] 2020-04-02 01:31
This is a duplicate of #427 . Just update the launcher to 1.4.6 and it should be solved.

**Closed by remyroy** 2020-04-02 01:31 UTC
