### ISSUE TITLE
Cdda Game launcher

### ISSUE THREAD

**Issue by SirClarke** [remyroy/CDDA-Game-Launcher#135] opened 2017-10-17 04:54 UTC
I've had a problem i can't update to the latest update as of a few days ago I'm on build number 6851 but there seems to be build by the number of 6861 just wanted to know if there is something wrong on my end or if its something to do with the Launcher. if it is on my end is there something i can do any help would be very appreciative thanks for your time.

**Comment by remyroy** [comment] 2017-10-17 04:56
This is a duplicate of #134

**Closed by remyroy** 2017-10-17 04:56 UTC
